### ISSUE TITLE
Error compiling RigidBodyDynamics library

### ISSUE THREAD

**Issue by AndresMenes** [balabibo/An-OpenFOAM-solver-focused-on-ship-free-running-maneuvering-simulations#2]
I've been trying to use your tutorial to learn how to do manouvering simulations. I compiled most of the libraries without any problems (HOsource, Oumsource and driven3dofmotion seem to work without problems, i even checked the numbers produced by HOsource and they match experimental data so that's great). However when i tried to do self propulsion the actuator disk doesn't move with the hull body. That's when i realised something is wrong with the other libraries like rigidbodydynamics and rigidbodymeshmotion. 

As you can see in the image im attaching it's not working. For sure i'm doing something wrong. Could you help me and give me some hints onto what i'm doing wrong? Maybe that's not the reason why the actuatordisk is not moving but looking at the code i think it might be, as it is not updating the cells position.

Thanks in advance @balabibo .

![image](https://github.com/user-attachments/assets/4f85da35-b2da-4c89-88e5-1aa1d5d516b5)

**Comment by balabibo** [comment]
Dear @AndresMenes 
    Thanks for your tests. I will check it and reply you later.

**Comment by balabibo** [comment]
Hi @AndresMenes 
I found that I miss a space at line 140 "DynamicList<spatialVector>detailDof_;" in rigidBodyModel.H. The correct one is DynamicList<spatialVector> detailDof_; you can clone the code and try compile it again. I also provide a "fvOptions" file here to represent a Kp505 propeller with HOsource, and you can try whether it works. Please let me any further problem you get. 
`
/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v2206                                 |
|   \\  /    A nd           | Website:  www.openfoam.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version         2.0;
    format          ascii;
    class           dictionary;
    object          fvOptions;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

disk1
{
    type         HOSource;
    rotationDir  right; // left
    KTCoeff (0.4873 -0.4399 0.0079 -0.0945 0 0);  // polynomial coefficients for KT-J: left to right, constant to 5th order
    KQCoeff (0.0694 -0.0561 0.0065 -0.0189 0 0);   // polynomial coefficients for KQ-J: left to right, constant to 5th order
    diskRadius     0.04637; 
    diskHub        0.18;
    diskDir         (-1 0 0);
    diskOrigin      (0 0 0);
    diskThickness    0.0064;
    diskRPS           5.071;
 
}
`
